version: '3'
services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_HOST: db
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
